#+title:  hugo的使用
#+description: 博客或静态内容生成工具


** 使用方法

   - 创建网站 hugo new site SITENAME
   - 写关于页面 hugo new about.md
   - 写文章 hugo new post/POSTNAME.md 
   - 创建主题 hugo new theme THEMENAME
   - 添加主题 git submodule add https://github.com/budparr/gohugo-theme-ananke.git themes/THEMENAME
   - 使用主题 echo 'theme = "ananke"' >> config.toml
   - 启动站点 hugo server -D
   - 使用模板 hugo server --theme=hyde
** 创建主题
*** 内容页
    内容页分两种:
    1. 单页面（在 content 目录下）
    2. 章节页（section page） （在 content 子目录下） 
    
      单页面的 Section 属性为空字符串， Type 属性为 page 
      章节页的 Section 属性为 页面所在的目录名
      
  
**** 给章节内容页面添加列表    

     默认列表页为：  content/post/_index.md  对应于 layouts/_default/list.html
     
     列表模板
     
     #+begin_src html
       <html  lang = "zh" >                                                          
         <head>                                                                       
           <meta  charset = "UTF-8" >                                                    
           <meta  name = "viewport"  content = "width=device-width, initial-scale=1.0" > 
           <meta  http-equiv = "X-UA-Compatible"  content = "ie=edge" >                  
           <title >列表页面  title >                                                     
             <head>                                                                         
               <body>                                                                       
       
                 {{  range .Pages }}                                                            
                 <div>                                                                        
                   <a  href = ".Permalink" >{{.Title}} />                                      
                 </div>                                                                          
                 {{  end  }}                                                                    
               </body>                                                                          
       </html>
               #+end_src
     
               
               上一页与下一页
               
               使用到了内容页模板中的 =.NextInSection= 和 =.PrevInSection= 变量, 他们表示当前章节中, 按时间倒序排列的文章集合的后一篇文章和前一篇文章.
               
*** 首页
    
    首页也属于列表页, 只是他是一个特殊的列表页. 如果没有给首页添加模板, 首页使用内容页的模板.

**** 在首页中展示各章节的文章列表

     #+begin_src html
网站首页                                              
                                                      
 新闻列表                                             
 {{ range where .Site.RegularPages "Section" "news" }}
 {{.Title}}                                           
 {{ end }}                                            
                                                      
 博文列表                                             
 {{ range where .Site.RegularPages "Section" "post" }}
 {{.Title}}                                           
 {{ end }}                                            

#+end_src

 这里主要用到两点
 - =.Site.RegularPages= 表示网站下面的所有节点内容, 具体到本例, 就是news和post目录下的所有文章
 - =where= 是一个函数, 用来查询集合中符合条件的项目.

 where 的语法: =where COLLECTION KEY [OPERATOR] MATCH=
 =where .Site.RegularPages "Section" "news"= 的含义就是, 查找出section属性的值为news的项目
 


 
